/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_expat_foundation_include_h__
#define _mulle_objc_expat_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use a2dcf4d0-48f2-4e74-8aef-13e42ef36b92 instead of expat if there are duplicate entries)
//    remove:             `mulle-sde dependency mark expat no-header`
//    rename:             `mulle-sde dependency|library set expat include whatever.h`
//    reorder:            `mulle-sde dependency move expat <up|down>`
//    toggle #include:    `mulle-sde dependency mark expat [no-]import`
//    toggle public:      `mulle-sde dependency mark expat [no-]public`
//    toggle optional:    `mulle-sde dependency mark expat [no-]require`
//    remove for platform:`mulle-sde dependency mark expat no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <expat.h>   // expat

#endif
