/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCExpatFoundation_include_h__
#define _MulleObjCExpatFoundation_include_h__

// How to tweak the following expat #include
//    remove:             `mulle-sourcetree mark expat no-header`
//    rename:             `mulle-sde dependency|library set expat include whatever.h`
//    toggle #import:     `mulle-sourcetree mark expat [no-]import`
//    toggle public:      `mulle-sourcetree mark expat [no-]public`
//    toggle optional:    `mulle-sourcetree mark expat [no-]require`
//    remove for os:      `mulle-sourcetree mark expat no-os-<osname>`
# include <expat.h>   // expat

#endif
