/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use 404EA57B-418F-4A2E-AF22-16970AFBBD03 instead of MulleObjCPlistFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleObjCPlistFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCPlistFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleObjCPlistFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleObjCPlistFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleObjCPlistFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleObjCPlistFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleObjCPlistFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleObjCPlistFoundation/MulleObjCPlistFoundation.h>   // MulleObjCPlistFoundation

// You can tweak the following #import with these commands.
// (Use 06CB6048-6DD4-42CF-ADA6-0A73CABDDD39 instead of MulleBase64 if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleBase64 no-header`
//    rename:             `mulle-sde dependency|library set MulleBase64 include whatever.h`
//    reorder:            `mulle-sde dependency move MulleBase64 <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleBase64 [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleBase64 [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleBase64 [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleBase64 no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleBase64/MulleBase64.h>   // MulleBase64

// You can tweak the following #import with these commands.
// (Use 8649B13A-A8E7-4E52-8E23-EBB3EFBFADF1 instead of MulleFoundation if there are duplicate entries)
//    remove:             `mulle-sde dependency mark MulleFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleFoundation include whatever.h`
//    reorder:            `mulle-sde dependency move MulleFoundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark MulleFoundation [no-]import`
//    toggle public:      `mulle-sde dependency mark MulleFoundation [no-]public`
//    toggle optional:    `mulle-sde dependency mark MulleFoundation [no-]require`
//    remove for platform:`mulle-sde dependency mark MulleFoundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <MulleFoundation/MulleFoundation.h>   // MulleFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCExpatFoundation-include.h")
#  include "_MulleObjCExpatFoundation-include.h"
# endif
#endif

