      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPlistFoundation) },      // 47a9beb6;MulleObjCLoader;e8aa8d92;MulleObjCPlistFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleObjCExpatParser), MULLE_OBJC_NO_CATEGORYID },      // e0ad20dd;MulleObjCExpatParser;;
      { @selector( NSPropertyListSerialization), @selector( MulleObjCExpatParser) },      // 87901b51;NSPropertyListSerialization;e0ad20dd;MulleObjCExpatParser
