      { @selector( MulleObjCLoader), @selector( MulleBase64) },      // 47a9beb6;MulleObjCLoader;22440994;MulleBase64
      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCPlistFoundation) },      // 47a9beb6;MulleObjCLoader;e8aa8d92;MulleObjCPlistFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( MulleObjCExpatParser), MULLE_OBJC_NO_CATEGORYID },      // e0ad20dd;MulleObjCExpatParser;;
      { @selector( NSArray), @selector( MulleObjCPropertyListPrinting_XML) },      // 233490fe;NSArray;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSData), @selector( MulleObjCPropertyListPrinting_XML) },      // 8fce7861;NSData;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSDate), @selector( MulleObjCPropertyListPrinting_XML) },      // cfcedd21;NSDate;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSDictionary), @selector( MulleObjCPropertyListPrinting_XML) },      // 8b2abcad;NSDictionary;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSNull), @selector( MulleObjCPropertyListPrinting_XML) },      // f0c42d79;NSNull;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSNumber), @selector( MulleObjCPropertyListPrinting_XML) },      // 8ba34f39;NSNumber;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSObject), @selector( MulleObjCPropertyListPrinting_XML) },      // b3a66256;NSObject;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( NSPropertyListSerialization), @selector( MulleObjCExpatParser) },      // 87901b51;NSPropertyListSerialization;e0ad20dd;MulleObjCExpatParser
      { @selector( NSString), @selector( MulleObjCPropertyListPrinting_XML) },      // 1994a171;NSString;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( _MulleObjCBoolNumber), @selector( MulleObjCPropertyListPrinting_XML) },      // 263c5445;_MulleObjCBoolNumber;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( _MulleObjCDoubleNumber), @selector( MulleObjCPropertyListPrinting_XML) },      // ae25b758;_MulleObjCDoubleNumber;9ae794e9;MulleObjCPropertyListPrinting_XML
      { @selector( _MulleObjCLongDoubleNumber), @selector( MulleObjCPropertyListPrinting_XML) },      // 4ec38072;_MulleObjCLongDoubleNumber;9ae794e9;MulleObjCPropertyListPrinting_XML
