/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_expat_foundation_include_h__
#define _mulle_objc_expat_foundation_include_h__

# include <expat.h>   // expat

#endif
