      { @selector( MulleObjCLoader), @selector( MulleObjCStandardFoundation) },      // 47a9beb6;MulleObjCLoader;ed704a42;MulleObjCStandardFoundation
      { @selector( MulleObjCExpatParser), MULLE_OBJC_NO_CATEGORYID },      // e0ad20dd;MulleObjCExpatParser;;
      { @selector( NSPropertyListSerialization), @selector( MulleObjCExpatParser) },      // 87901b51;NSPropertyListSerialization;e0ad20dd;MulleObjCExpatParser
